#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
	sctl)
		source $(dirname $0)/rc
		shift

		docker run --rm -it \
			--link $(docker inspect --format '{{ .Name }}' $(cat "$TR_ROOT"/.cid)):supervisord \
			$TR_IMAGE_NAME \
			bash -c "supervisorctl -s \${SUPERVISORD_PORT_9001_TCP/tcp/http} $@"

	;;

	help)
		cat && echo "    sctl                                            Run interactive console on task supervisor"
	;;

esac
